version: '3.8'
services:
  server:
    build: ./server
    volumes:
      - ../hugoSite/content/:/usr/src/content
      - ../hugoSite:/usr/src/hugoSite
    environment:
      - HUGO_SITE_DIR=/usr/src/hugoSite
    restart: always
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "6768:80"
    depends_on:
      - server
    restart: always
